### ISSUE TITLE
java.lang.IllegalStateException on issue open

### ISSUE THREAD

**Issue by tstupka** [junichi11/netbeans-github-issues-plugin#2] opened 2015-01-05 14:11 UTC
java.lang.IllegalStateException
	at org.objectweb.asm.tree.ClassNode.<init>(Unknown Source)
	at org.parboiled.transform.ParserClassNode.<init>(ParserClassNode.java:41)
	at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:43)
	at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:38)
	at org.parboiled.Parboiled.createParser(Parboiled.java:54)
Caused: java.lang.RuntimeException: Error creating extended parser class: null
	at org.parboiled.Parboiled.createParser(Parboiled.java:58)
	at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:92)
	at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:71)
	at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:52)
	at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:45)
	at com.junichi11.netbeans.modules.github.issues.issue.ui.GitHubIssuePanel.update(GitHubIssuePanel.java:241)
	at com.junichi11.netbeans.modules.github.issues.issue.GitHubIssueController.<init>(GitHubIssueController.java:76)
	at com.junichi11.netbeans.modules.github.issues.issue.GitHubIssue.getController(GitHubIssue.java:207)
	at com.junichi11.netbeans.modules.github.issues.issue.GitHubIssueProvider.getController(GitHubIssueProvider.java:108)
	at com.junichi11.netbeans.modules.github.issues.issue.GitHubIssueProvider.getController(GitHubIssueProvider.java:54)
	at org.netbeans.modules.bugtracking.IssueImpl.getController(IssueImpl.java:211)
	at org.netbeans.modules.bugtracking.ui.issue.IssueTopComponent.setIssue(IssueTopComponent.java:234)
	at org.netbeans.modules.bugtracking.ui.issue.IssueTopComponent.find(IssueTopComponent.java:615)
	at org.netbeans.modules.bugtracking.ui.issue.IssueTopComponent.find(IssueTopComponent.java:594)
	at org.netbeans.modules.bugtracking.ui.issue.IssueAction$1.run(IssueAction.java:104)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by junichi11** [comment] 2015-01-06 02:13
I'll fix it.
Thanks!

**Comment by tstupka** [comment] 2015-01-06 12:22
https://github.com/tstupka/koliba 

happened with every issue i've tried to open

**Comment by junichi11** [comment] 2015-01-06 15:53
I run the module with java 7 and 8. but it works fine... This may be pegdown(or parboiled) problem. Can you run the plugin with java7?

![nb-github-issues-issue2](https://cloud.githubusercontent.com/assets/738383/5630634/e91fee5c-9602-11e4-8fb1-ae2bfdd54885.png)

#### my environments

Product Version: NetBeans IDE 8.0.2 (Build 201408251540)
Java: 1.7.0_72; Java HotSpot(TM) Client VM 24.72-b04
Runtime: Java(TM) SE Runtime Environment 1.7.0_72-b14
System: Linux version 3.2.0-74-generic-pae running on i386; UTF-8; ja_JP (nb)

Product Version: NetBeans IDE 8.0.2 (Build 201408251540)
Java: 1.8.0_25; Java HotSpot(TM) Client VM 25.25-b02
Runtime: Java(TM) SE Runtime Environment 1.8.0_25-b17
System: Linux version 3.2.0-74-generic-pae running on i386; UTF-8; ja_JP (nb)

**Comment by tstupka** [comment] 2015-01-06 16:33
hm, i've run it with

Product Version: NetBeans IDE Dev (Build 20150106-73fb82d2b493)
Java: 1.7.0_65; Java HotSpot(TM) 64-Bit Server VM 24.65-b04
Runtime: Java(TM) SE Runtime Environment 1.7.0_65-b20
System: Mac OS X version 10.10 running on x86_64; UTF-8; en_US (nb)

**Comment by junichi11** [comment] 2015-01-07 01:12
Thanks! 
Umm, I'm not sure the cause yet.
I want to run the plugin on Mac OS. But unfortunately I don't have it.

**Comment by Yserz** [comment] 2015-03-28 20:00
I tested it with Java 8 and Mac OS X and I can't reproduce it too. Maybe there's a missing permission for the OAuth key (just a guess)?

Product Version: NetBeans IDE 8.0.2 (Build 201411181905)
Java: 1.8.0; Java HotSpot(TM) 64-Bit Server VM 25.0-b70
Runtime: Java(TM) SE Runtime Environment 1.8.0-b132
System: Mac OS X version 10.10.2 running on x86_64; UTF-8; de_DE (nb)

**Comment by lilo003** [comment] 2015-07-24 10:56
I'm also with the same error, any idea to fix this?
thanks

**Comment by junichi11** [comment] 2015-07-24 11:58
@Yserz Thanks for testing it :)

@lilo003 
I'll try to update the pegdown version.

**Comment by junichi11** [comment] 2015-07-24 12:25
@lilo003 
I've just updated the pegdown version. Could you try to use the following?: 
https://github.com/junichi11/netbeans-github-issues-plugin/releases/tag/v0.1.1 (0.1.1.1)

**Comment by lilo003** [comment] 2015-07-24 12:36
Is great! It worked
I'm already using, your great tool!
Thanks

**Comment by junichi11** [comment] 2015-07-24 12:39
Thanks for testing it :)
I'll close this issue.

**Closed by junichi11** 2015-07-24 12:39 UTC
Labels: bug
